<a href="https://colab.research.google.com/github/EnricoHuber/TensorFlow-Review/blob/main/RNN_and_Natural_Language_Processing_with_TF_and_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
%tensorflow_version 2.x
from keras.datasets import imdb
from keras.preprocessing import sequence
import keras
import tensorflow as tf
import os
import numpy as np
from tensorflow import keras

VOCAB_SIZE = 88584

MAXLEN = 250
BATCH_SIZE = 64

(train_data, train_labels), (test_data, test_labels) = imdb.load_data(num_words = VOCAB_SIZE)

17465344/17464789 [==============================] - 0s 0us/step


<string>:6: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/datasets/imdb.py:159: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  x_train, y_train = np.array(xs[:idx]), np.array(labels[:idx])
/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/datasets/imdb.py:160: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 

In [3]:
train_data[0], len(train_data[0])

([1,
  14,
  22,
  16,
  43,
  530,
  973,
  1622,
  1385,
  65,
  458,
  4468,
  66,
  3941,
  4,
  173,
  36,
  256,
  5,
  25,
  100,
  43,
  838,
  112,
  50,
  670,
  22665,
  9,
  35,
  480,
  284,
  5,
  150,
  4,
  172,
  112,
  167,
  21631,
  336,
  385,
  39,
  4,
  172,
  4536,
  1111,
  17,
  546,
  38,
  13,
  447,
  4,
  192,
  50,
  16,
  6,
  147,
  2025,
  19,
  14,
  22,
  4,
  1920,
  4613,
  469,
  4,
  22,
  71,
  87,
  12,
  16,
  43,
  530,
  38,
  76,
  15,
  13,
  1247,
  4,
  22,
  17,
  515,
  17,
  12,
  16,
  626,
  18,
  19193,
  5,
  62,
  386,
  12,
  8,
  316,
  8,
  106,
  5,
  4,
  2223,
  5244,
  16,
  480,
  66,
  3785,
  33,
  4,
  130,
  12,
  16,
  38,
  619,
  5,
  25,
  124,
  51,
  36,
  135,
  48,
  25,
  1415,
  33,
  6,
  22,
  12,
  215,
  28,
  77,
  52,
  5,
  14,
  407,
  16,
  82,
  10311,
  8,
  4,
  107,
  117,
  5952,
  15,
  256,
  4,
  31050,
  7,
  3766,
  5,
  723,
  36,
  71,
  43,
  530,
  476,
  26,
  400,
  317,
  46,
  7,


Preprocessing: add padding because each review has a different length

In [4]:
train_data = sequence.pad_sequences(train_data, MAXLEN)
test_data = sequence.pad_sequences(test_data, MAXLEN)

In [5]:
train_data[0], len(train_data[0])

(array([    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     1,    14,    22,    16,
           43,   530,   973,  1622,  1385,    65,   458,  4468,    66,
         3941,     4,   173,    36,   256,     5,    25,   100,    43,
          838,   112,    50,   670, 22665,     9,    35,   480,   284,
            5,   150,     4,   172,   112,   167, 21631,   336,   385,
           39,     4,   172,  4536,  1111,    17,   546,    38,    13,
          447,     4,   192,    50,    16,     6,   147,  2025,    19,
           14,    22,     4,  1920,  4613,   469,     4,    22,    71,
           87,    12,    16,    43,   530,    38,    76,    15,    13,
         1247,     4,    22,    17,   515,    17,    12,    16,   626,
           18, 19193,     5,    62,   386,    12,     8,   316,     8,
      

Create the model

In [6]:
model = tf.keras.Sequential([
  tf.keras.layers.Embedding(VOCAB_SIZE, 32),
  tf.keras.layers.LSTM(32),
  tf.keras.layers.Dense(1, activation='sigmoid')
])

In [7]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, None, 32)          2834688   
_________________________________________________________________
lstm (LSTM)                  (None, 32)                8320      
_________________________________________________________________
dense (Dense)                (None, 1)                 33        
Total params: 2,843,041
Trainable params: 2,843,041
Non-trainable params: 0
_________________________________________________________________


Train the model

In [11]:
%%time
model.compile(loss="binary_crossentropy",optimizer="rmsprop",metrics=['acc'])

history = model.fit(train_data, train_labels, epochs=2, validation_split=0.2)

Epoch 1/2
625/625 [==============================] - 17s 24ms/step - loss: 0.1892 - acc: 0.9291 - val_loss: 0.2985 - val_acc: 0.8932
Epoch 2/2
625/625 [==============================] - 14s 22ms/step - loss: 0.1429 - acc: 0.9503 - val_loss: 0.2874 - val_acc: 0.8922
CPU times: user 32.9 s, sys: 2.5 s, total: 35.4 s
Wall time: 30.7 s


Make predictions

In [15]:
word_index = imdb.get_word_index()

def encode_text(text):
  tokens = keras.preprocessing.text.text_to_word_sequence(text)
  tokens = [word_index[word] if word in word_index else 0 for word in tokens]
  return sequence.pad_sequences([tokens], MAXLEN)[0]

text = "that movie was just amazing, so amazing"
encoded = encode_text(text)
print(encoded)

[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0  12  17  13  4

In [22]:
word_index, word_index['amazing']

({'fawn': 34701,
  'tsukino': 52006,
  'nunnery': 52007,
  'sonja': 16816,
  'vani': 63951,
  'woods': 1408,
  'spiders': 16115,
  'hanging': 2345,
  'woody': 2289,
  'trawling': 52008,
  "hold's": 52009,
  'comically': 11307,
  'localized': 40830,
  'disobeying': 30568,
  "'royale": 52010,
  "harpo's": 40831,
  'canet': 52011,
  'aileen': 19313,
  'acurately': 52012,
  "diplomat's": 52013,
  'rickman': 25242,
  'arranged': 6746,
  'rumbustious': 52014,
  'familiarness': 52015,
  "spider'": 52016,
  'hahahah': 68804,
  "wood'": 52017,
  'transvestism': 40833,
  "hangin'": 34702,
  'bringing': 2338,
  'seamier': 40834,
  'wooded': 34703,
  'bravora': 52018,
  'grueling': 16817,
  'wooden': 1636,
  'wednesday': 16818,
  "'prix": 52019,
  'altagracia': 34704,
  'circuitry': 52020,
  'crotch': 11585,
  'busybody': 57766,
  "tart'n'tangy": 52021,
  'burgade': 14129,
  'thrace': 52023,
  "tom's": 11038,
  'snuggles': 52025,
  'francesco': 29114,
  'complainers': 52027,
  'templarios': 52125,

In [17]:
print(encode_text('i love that movie, it is great'))

[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0  10 116  12  1

In [18]:
reverse_word_index = {value: key for (key, value) in word_index.items()}

def decode_integers(integers):
    PAD = 0
    text = ""
    for num in integers:
      if num != PAD:
        text += reverse_word_index[num] + " "

    return text[:-1]
  
print(decode_integers(encoded))

that movie was just amazing so amazing


In [21]:
reverse_word_index

{34701: 'fawn',
 52006: 'tsukino',
 52007: 'nunnery',
 16816: 'sonja',
 63951: 'vani',
 1408: 'woods',
 16115: 'spiders',
 2345: 'hanging',
 2289: 'woody',
 52008: 'trawling',
 52009: "hold's",
 11307: 'comically',
 40830: 'localized',
 30568: 'disobeying',
 52010: "'royale",
 40831: "harpo's",
 52011: 'canet',
 19313: 'aileen',
 52012: 'acurately',
 52013: "diplomat's",
 25242: 'rickman',
 6746: 'arranged',
 52014: 'rumbustious',
 52015: 'familiarness',
 52016: "spider'",
 68804: 'hahahah',
 52017: "wood'",
 40833: 'transvestism',
 34702: "hangin'",
 2338: 'bringing',
 40834: 'seamier',
 34703: 'wooded',
 52018: 'bravora',
 16817: 'grueling',
 1636: 'wooden',
 16818: 'wednesday',
 52019: "'prix",
 34704: 'altagracia',
 52020: 'circuitry',
 11585: 'crotch',
 57766: 'busybody',
 52021: "tart'n'tangy",
 14129: 'burgade',
 52023: 'thrace',
 11038: "tom's",
 52025: 'snuggles',
 29114: 'francesco',
 52027: 'complainers',
 52125: 'templarios',
 40835: '272',
 52028: '273',
 52130: 'zaniacs',

In [29]:
def predict(text):
  encoded_text = encode_text(text)
  pred = np.zeros((1,250))
  pred[0] = encoded_text
  result = model.predict(pred) 
  print(result[0])

positive_review = "That movie was great fantastic superbe great! really loved it and would great watch again because it was amazingly great"
predict(positive_review)

negative_review = "that movie really sucked. I hated it and wouldn't watch it again. Was one of the worst things I've ever watched"
predict(negative_review)

[0.87474376]
[0.28881937]


# Play Generator

In [9]:
%tensorflow_version 2.x  # this line is not required unless you are in a notebook
from keras.preprocessing import sequence
import keras
import tensorflow as tf
import os
import numpy as np

`%tensorflow_version` only switches the major version: 1.x or 2.x.
You set: `2.x  # this line is not required unless you are in a notebook`. This will be interpreted as: `2.x`.


TensorFlow is already loaded. Please restart the runtime to change versions.


In [10]:
path_to_file = tf.keras.utils.get_file('shakespeare.txt', 'https://storage.googleapis.com/download.tensorflow.org/data/shakespeare.txt')

1122304/1115394 [==============================] - 0s 0us/step


In [200]:
from google.colab import files
path_to_file = list(files.upload().keys())[0]

Saving divinacommedia.txt to divinacommedia (1).txt


In [201]:
# Read, then decode for py2 compat.
text = open(path_to_file, 'rb').read().decode(encoding='utf-8')
# length of text is the number of characters in it
print ('Length of text: {} characters'.format(len(text)))

Length of text: 552028 characters


In [202]:
print(text[:500])

INFERNO




Inferno
Canto I


Nel mezzo del cammin di nostra vita
mi ritrovai per una selva oscura,
ché la diritta via era smarrita.

Ahi quanto a dir qual era è cosa dura
esta selva selvaggia e aspra e forte
che nel pensier rinova la paura!

Tant’ è amara che poco è più morte;
ma per trattar del ben ch’i’ vi trovai,
dirò de l’altre cose ch’i’ v’ho scorte.

Io non so ben ridir com’ i’ v’intrai,
tant’ era pien di sonno a quel punto
che la verace via abbandonai.

Ma poi ch


In [203]:
vocab = sorted(set(text))
# Creating a mapping from unique characters to indices
char2idx = {u:i for i, u in enumerate(vocab)}
idx2char = np.array(vocab)

def text_to_int(text):
  return np.array([char2idx[c] for c in text])

text_as_int = text_to_int(text)

In [204]:
text_as_int

array([20, 23, 17, ...,  8,  1,  0])

In [205]:
print("Text:", text[:13])
print("Encoded:", text_to_int(text[:13]))

Text: INFERNO



Encoded: [20 23 17 16 27 23 24  1  0  1  0  1  0]


In [206]:
def int_to_text(ints):
  try:
    ints = ints.numpy()
  except:
    pass
  return ''.join(idx2char[ints])

print(int_to_text(text_as_int[:13]))

INFERNO





In [207]:
seq_length = 100  # length of sequence for a training example
examples_per_epoch = len(text)//(seq_length+1)

# Create training examples / targets
char_dataset = tf.data.Dataset.from_tensor_slices(text_as_int)

In [208]:
sequences = char_dataset.batch(seq_length+1, drop_remainder=True)

In [209]:
def split_input_target(chunk):  # for the example: hello
    input_text = chunk[:-1]  # hell
    target_text = chunk[1:]  # ello
    return input_text, target_text  # hell, ello

dataset = sequences.map(split_input_target)  # we use map to apply the above function to every entry

In [210]:
for x, y in dataset.take(2):
  print("\n\nEXAMPLE\n")
  print("INPUT")
  print(int_to_text(x))
  print("\nOUTPUT")
  print(int_to_text(y))



EXAMPLE

INPUT
INFERNO




Inferno
Canto I


Nel mezzo del cammin di nostra vita
mi ritrovai per una selv

OUTPUT
NFERNO




Inferno
Canto I


Nel mezzo del cammin di nostra vita
mi ritrovai per una selva


EXAMPLE

INPUT
 oscura,
ché la diritta via era smarrita.

Ahi quanto a dir qual era è cosa dura
esta selva selv

OUTPUT
oscura,
ché la diritta via era smarrita.

Ahi quanto a dir qual era è cosa dura
esta selva selva


In [211]:
BATCH_SIZE = 64
VOCAB_SIZE = len(vocab)  # vocab is number of unique characters
EMBEDDING_DIM = 256
RNN_UNITS = 1024

# Buffer size to shuffle the dataset
# (TF data is designed to work with possibly infinite sequences,
# so it doesn't attempt to shuffle the entire sequence in memory. Instead,
# it maintains a buffer in which it shuffles elements).
BUFFER_SIZE = 10000

data = dataset.shuffle(BUFFER_SIZE).batch(BATCH_SIZE, drop_remainder=True)

In [212]:
def build_model(vocab_size, embedding_dim, rnn_units, batch_size):
  model = tf.keras.Sequential([
    tf.keras.layers.Embedding(vocab_size, embedding_dim,
                              batch_input_shape=[batch_size, None]),
    tf.keras.layers.LSTM(rnn_units,
                        return_sequences=True,
                        stateful=True,
                        recurrent_initializer='glorot_uniform'),
    tf.keras.layers.Dense(vocab_size)
  ])
  return model

model = build_model(VOCAB_SIZE,EMBEDDING_DIM, RNN_UNITS, BATCH_SIZE)
model.summary()

Model: "sequential_14"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_14 (Embedding)     (64, None, 256)           20480     
_________________________________________________________________
lstm_14 (LSTM)               (64, None, 1024)          5246976   
_________________________________________________________________
dense_14 (Dense)             (64, None, 80)            82000     
Total params: 5,349,456
Trainable params: 5,349,456
Non-trainable params: 0
_________________________________________________________________


In [213]:
for input_example_batch, target_example_batch in data.take(1):
  example_batch_predictions = model(input_example_batch)  # ask our model for a prediction on our first batch of training data (64 entries)
  print(example_batch_predictions.shape, "# (batch_size, sequence_length, vocab_size)")  # print out the output shape

(64, 100, 80) # (batch_size, sequence_length, vocab_size)


In [214]:
print(len(example_batch_predictions))
print(example_batch_predictions)

64
tf.Tensor(
[[[ 1.33245182e-03 -1.05911251e-02 -2.82842224e-03 ... -1.66134792e-03
   -2.58652354e-03 -3.22872121e-03]
  [ 1.64977275e-04 -1.04720118e-02 -5.03442716e-03 ... -1.13608246e-03
   -1.52693200e-03 -3.75338225e-03]
  [ 1.15443429e-03 -7.55199837e-03 -4.15832596e-03 ... -6.08621398e-04
    8.38520005e-04 -4.31921892e-03]
  ...
  [ 5.17871324e-03 -4.71815234e-03  1.10154673e-02 ... -1.26928855e-02
   -7.75749097e-04 -1.37290973e-02]
  [ 4.95901611e-03 -2.80415034e-03  1.13705220e-02 ... -1.24233328e-02
    1.90158142e-03 -1.74540393e-02]
  [-1.84347620e-04 -2.50077108e-03  1.48405489e-02 ... -1.16546517e-02
    3.39146005e-03 -1.14033325e-02]]

 [[-1.56480330e-03 -3.92041076e-03 -3.34561616e-03 ...  6.64902909e-04
    1.61242788e-04  1.63482316e-03]
  [-2.59714341e-03  3.73497349e-03 -2.59578158e-03 ... -5.74583607e-03
   -4.65083052e-04  5.70950843e-03]
  [-6.19565137e-04  5.79857826e-03  1.11855217e-03 ... -1.24334730e-03
    2.19076686e-03  4.27990453e-03]
  ...
  [ 8.910

In [215]:
pred = example_batch_predictions[0]
print(len(pred))
print(pred)

100
tf.Tensor(
[[ 0.00133245 -0.01059113 -0.00282842 ... -0.00166135 -0.00258652
  -0.00322872]
 [ 0.00016498 -0.01047201 -0.00503443 ... -0.00113608 -0.00152693
  -0.00375338]
 [ 0.00115443 -0.007552   -0.00415833 ... -0.00060862  0.00083852
  -0.00431922]
 ...
 [ 0.00517871 -0.00471815  0.01101547 ... -0.01269289 -0.00077575
  -0.0137291 ]
 [ 0.00495902 -0.00280415  0.01137052 ... -0.01242333  0.00190158
  -0.01745404]
 [-0.00018435 -0.00250077  0.01484055 ... -0.01165465  0.00339146
  -0.01140333]], shape=(100, 80), dtype=float32)


In [216]:
sampled_indices = tf.random.categorical(pred, num_samples=1)

# now we can reshape that array and convert all the integers to numbers to see the actual characters
sampled_indices = np.reshape(sampled_indices, (1, -1))[0]
predicted_chars = int_to_text(sampled_indices)

predicted_chars  # and this is what the model predicted for training sequence 1

'i-Góy;bùlM»BIéA-jB“ó\r\rLx.hjäQé)-,dhPAV’ùCä\nGFöX(R:UóBeU—A\n—»fc“SïCeË”pl«Do b\nvghmRcFuZ!ù.otOpA?\nä“ëC'

In [217]:
time_pred = pred[0]
print(len(time_pred))
print(time_pred)

80
tf.Tensor(
[ 0.00133245 -0.01059113 -0.00282842 -0.0019922   0.00511097 -0.00141671
 -0.00622758 -0.00596633 -0.00518096 -0.00060011  0.00011138 -0.00125098
 -0.00067144  0.00395987 -0.0047492  -0.00449809 -0.00408437 -0.00027879
 -0.00553773  0.00583159 -0.00224669  0.00146567 -0.00432798  0.00354438
  0.00380942 -0.00105689  0.00069968 -0.00229289  0.00412858 -0.00342333
  0.00232891 -0.00352259 -0.00034222  0.00398655  0.00270514 -0.00204034
 -0.00360584  0.00139216  0.00070908  0.007311   -0.00184076 -0.00070783
  0.00419019  0.00048392  0.0001505   0.00605221 -0.00111868  0.00256147
 -0.00420602  0.00172855  0.00158587  0.00280014  0.00228758 -0.00058705
  0.00028772 -0.00288002  0.00120808 -0.00240859  0.00370099 -0.00118818
 -0.00051706  0.00141375  0.00140487 -0.00159747  0.00132062 -0.00401112
  0.00472954  0.00202247 -0.00302759 -0.00340363 -0.00329895  0.00366799
  0.00261421 -0.00521299 -0.00030221 -0.00292788 -0.00012246 -0.00166135
 -0.00258652 -0.00322872], shape=(80,

In [218]:
def loss(labels, logits):
  return tf.keras.losses.sparse_categorical_crossentropy(labels, logits, from_logits=True)

In [219]:
model.compile(optimizer='adam', loss=loss)

In [220]:
checkpoint_dir = './training_checkpoints'
# Name of the checkpoint files
checkpoint_prefix = os.path.join(checkpoint_dir, "ckpt_{epoch}")

checkpoint_callback=tf.keras.callbacks.ModelCheckpoint(
    filepath=checkpoint_prefix,
    save_weights_only=True)

In [221]:
history = model.fit(data, epochs=70, callbacks=[checkpoint_callback])

Epoch 1/70
85/85 [==============================] - 7s 56ms/step - loss: 3.1668
Epoch 2/70
85/85 [==============================] - 6s 55ms/step - loss: 2.1216
Epoch 3/70
85/85 [==============================] - 6s 56ms/step - loss: 1.8980
Epoch 4/70
85/85 [==============================] - 6s 56ms/step - loss: 1.7613
Epoch 5/70
85/85 [==============================] - 6s 55ms/step - loss: 1.6535
Epoch 6/70
85/85 [==============================] - 6s 55ms/step - loss: 1.5702
Epoch 7/70
85/85 [==============================] - 6s 56ms/step - loss: 1.5015
Epoch 8/70
85/85 [==============================] - 6s 55ms/step - loss: 1.4571
Epoch 9/70
85/85 [==============================] - 6s 55ms/step - loss: 1.4001
Epoch 10/70
85/85 [==============================] - 6s 55ms/step - loss: 1.3636
Epoch 11/70
85/85 [==============================] - 6s 55ms/step - loss: 1.3201
Epoch 12/70
85/85 [==============================] - 5s 55ms/step - loss: 1.2839
Epoch 13/70
85/85 [==================

In [222]:
model = build_model(VOCAB_SIZE, EMBEDDING_DIM, RNN_UNITS, batch_size=1)

In [223]:
model.load_weights(tf.train.latest_checkpoint(checkpoint_dir))
model.build(tf.TensorShape([1, None]))

In [224]:
def generate_text(model, start_string):
  # Evaluation step (generating text using the learned model)

  # Number of characters to generate
  num_generate = 800

  # Converting our start string to numbers (vectorizing)
  input_eval = [char2idx[s] for s in start_string]
  input_eval = tf.expand_dims(input_eval, 0)

  # Empty string to store our results
  text_generated = []

  # Low temperatures results in more predictable text.
  # Higher temperatures results in more surprising text.
  # Experiment to find the best setting.
  temperature = 0.2

  # Here batch size == 1
  model.reset_states()
  for i in range(num_generate):
      predictions = model(input_eval)
      # remove the batch dimension
    
      predictions = tf.squeeze(predictions, 0)

      # using a categorical distribution to predict the character returned by the model
      predictions = predictions / temperature
      predicted_id = tf.random.categorical(predictions, num_samples=1)[-1,0].numpy()

      # We pass the predicted character as the next input to the model
      # along with the previous hidden state
      input_eval = tf.expand_dims([predicted_id], 0)

      text_generated.append(idx2char[predicted_id])

  return (start_string + ''.join(text_generated))

In [232]:
inp = input("Type a starting string: ")
print('\n')
print(generate_text(model, inp))

Type a starting string: Possa


Possa è fatta fella
per non esser corretto a me destro.

Poi, profetando ciascun come corte
per lo dempre d’ogne mortal, fu stanan li avvanni».

Or vi fosse tutto presto loco,
perché ’l discerni rimirando in Dio.

Fatto m’hai lieto, e così questo pretro
altro non è ch’un lume di suo raggio,

più che in altra convien che si mova
la mente, amando, di paradiso.

Indi la valle, come ’l dì fu spento,
da Pratomagno al gran giogo coperse
di nebbia; e ’l collo d’una di lor tormai che ’l disio di vento,
e non le scusa non veder lo danno.

Non disse Cristo al suo primo convento:
‘Andate, sì che possa a parola
da la qual furon maggior valle in fornace.

Poscia per indi ond’ era pria venuta,
l’aguglia vidi scender giù ne l’arca
del carro e lasciar la man destra mi lasciai.

Quan
